

export const MY_LOGS_REQUEST = "MY_LOGS_REQUEST";
export const MY_LOGS_SUCCESS = "MY_LOGS_SUCCESS";
export const MY_LOGS_FAIL = "MY_LOGS_FAIL";

export const LOGS_DETAILS_REQUEST = "LOGS_DETAILS_REQUEST";
export const LOGS_DETAILS_SUCCESS = "LOGS_DETAILS_SUCCESS";
export const LOGS_DETAILS_FAIL = "LOGS_DETAILS_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";
