export const ALL_NOTIFICATIONS_REQUEST = "ALL_NOTIFICATIONS_REQUEST";
export const ALL_NOTIFICATIONS_SUCCESS = "ALL_NOTIFICATIONS_SUCCESS";
export const ALL_NOTIFICATIONS_FAIL = "ALL_NOTIFICATIONS_FAIL";

export const ALL_NOTIFICATIONS_ALERT_REQUEST = "ALL_NOTIFICATIONS_ALERT_REQUEST";
export const ALL_NOTIFICATIONS_ALERT_SUCCESS = "ALL_NOTIFICATIONS_ALERT_SUCCESS";
export const ALL_NOTIFICATIONS_ALERT_FAIL = "ALL_NOTIFICATIONS_ALERT_FAIL";

export const DELETE_NOTIFICATION_REQUEST = "DELETE_NOTIFICATION_REQUEST";
export const DELETE_NOTIFICATION_SUCCESS = "DELETE_NOTIFICATION_SUCCESS";
export const DELETE_NOTIFICATION_RESET = "DELETE_NOTIFICATION_RESET";
export const DELETE_NOTIFICATION_FAIL = "DELETE_NOTIFICATION_FAIL";

export const UPDATE_NOTIFICATION_REQUEST = "UPDATE_NOTIFICATION_REQUEST";
export const UPDATE_NOTIFICATION_SUCCESS = "UPDATE_NOTIFICATION_SUCCESS";
export const UPDATE_NOTIFICATION_RESET = "UPDATE_NOTIFICATION_RESET";
export const UPDATE_NOTIFICATION_FAIL = "UPDATE_NOTIFICATION_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

// SSE Real-time notifications
export const SSE_NOTIFICATION_RECEIVED = "SSE_NOTIFICATION_RECEIVED";
export const SSE_NOTIFICATION_MARK_READ = "SSE_NOTIFICATION_MARK_READ";
export const SSE_NOTIFICATION_CLEAR_ALL = "SSE_NOTIFICATION_CLEAR_ALL";
export const SSE_CONNECTION_STATUS = "SSE_CONNECTION_STATUS";